name: dart_aoc18
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: pascalwelsch <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  test: ^1.0.0

dev_dependencies:
